### ISSUE TITLE
@Value 사용 개선

### ISSUE THREAD

**Issue by KyeongMoon** [chabak-map/backend#11]
## 개요
프로젝트내 사용되고 있는 `@Value` 를 개선한다.

## 문제
```java
public AES256(@Value("{secret.USER_INFO_32BIT_KEY}") String key) {
		this.key = key;
		this.iv = key.substring(0, 16);
	}
```

`@Value` 의 사용은 다음의 문제점을 가지고 있다.

* 값이 올바르지 않은 경우 ( 공백 혹은 오타 혹은 패턴 ) 검증하지 못한다.
* `@Value`의 파라매터로 string 을 사용하기 때문에 중복이 발생한다.

따라서 런타임에 properties 설정이 잘못된 것을 알 수 있다.

## 개선방향
컴파일 타임에 이를 인지할 수 있도록 한다.

spring 에서 제공 하는 기능인 `@ConfigurationProperties` 를 사용하여,
별도의 클래스로 값을 받을 수 있도록 하고 생성 시점에 값 검증을 추가한다.

다른 클래스에서 Properties 가 필요한 경우 생성한 클래스에서 값을 꺼내와 사용한다.

참고 : https://www.baeldung.com/configuration-properties-in-spring-boot

**Comment by hjun-park** [comment]
`@ConfigurationProperties` 적용 완료하였습니다.

관련 커밋입니다 : 99b31c0

**Comment by KyeongMoon** [comment]
@hjun-park 님
코멘트 달았습니다.

https://github.com/chabak-map/backend/commit/99b31c076a0bda021c5c4f77b5db14bf9415cb09#commitcomment-61665055
