### ISSUE TITLE
나의 포스트 500 에러

### ISSUE THREAD

**Issue by kimjihw** [chabak-map/backend#24]
![image](https://user-images.githubusercontent.com/57333984/144739808-0175467c-8345-439f-9e42-cd70956b0cb0.png)

**Comment by hjun-park** [comment]
최근 관리자/회원/비회원의 접근 제어를 위해 인터셉터 계층을 추가함에 따라 JWT 토큰 내용 일부가 수정되었습니다. 
기존 로그인하던 계정을 새로 갱신하였고 관리자 권한 부여 해드렸습니다.

관련 커밋 : 54b4ae498a9d4a229046dede37bfb4d007513b7a
